
import { Radical } from './types';

export const RADICALS: Radical[] = [
  // Existing ones refined
  { character: '人', variant: '亻', pinyin: 'rén', meaning: 'Person', difficulty: 1, examples: ['你', '他', '从'] },
  { character: '火', variant: '灬', pinyin: 'huǒ', meaning: 'Fire', difficulty: 1, examples: ['灯', '热', '烧'] },
  { character: '水', variant: '氵', pinyin: 'shuǐ', meaning: 'Water', difficulty: 1, examples: ['河', '海', '洗'] },
  { character: '木', pinyin: 'mù', meaning: 'Wood / Tree', difficulty: 1, examples: ['林', '森', '板'] },
  { character: '口', pinyin: 'kǒu', meaning: 'Mouth', difficulty: 1, examples: ['吃', '喝', '喊'] },
  { character: '心', variant: '忄', pinyin: 'xīn', meaning: 'Heart', difficulty: 2, examples: ['想', '感', '怕'] },
  { character: '言', variant: '讠', pinyin: 'yán', meaning: 'Speech', difficulty: 2, examples: ['说', '话', '语'] },
  { character: '日', pinyin: 'rì', meaning: 'Sun / Day', difficulty: 1, examples: ['明', '晚', '昨'] },
  { character: '月', pinyin: 'yuè', meaning: 'Moon / Month / Flesh', difficulty: 2, examples: ['朋', '肥', '背'] },
  { character: '手', variant: '扌', pinyin: 'shǒu', meaning: 'Hand', difficulty: 2, examples: ['打', '推', '拿'] },
  { character: '女', pinyin: 'nǚ', meaning: 'Woman', difficulty: 1, examples: ['妈', '姐', '好'] },
  { character: '子', pinyin: 'zǐ', meaning: 'Child / Son', difficulty: 1, examples: ['学', '孩', '孙'] },
  { character: '山', pinyin: 'shān', meaning: 'Mountain', difficulty: 1, examples: ['岩', '峰', '岭'] },
  { character: '土', pinyin: 'tǔ', meaning: 'Earth / Soil', difficulty: 1, examples: ['地', '场', '圣'] },
  { character: '门', pinyin: 'mén', meaning: 'Door / Gate', difficulty: 2, examples: ['问', '间', '闭'] },
  { character: '马', pinyin: 'mǎ', meaning: 'Horse', difficulty: 2, examples: ['妈', '骑', '驾'] },
  { character: '目', pinyin: 'mù', meaning: 'Eye', difficulty: 2, examples: ['看', '眠', '眨'] },
  { character: '禾', pinyin: 'hé', meaning: 'Grain', difficulty: 2, examples: ['私', '秋', '科'] },
  { character: '玉', variant: '王', pinyin: 'yù', meaning: 'Jade / King', difficulty: 2, examples: ['玩', '班', '珍'] },
  { character: '足', variant: '⻊', pinyin: 'zú', meaning: 'Foot', difficulty: 2, examples: ['跑', '踢', '路'] },

  // New Additions to reach 100+
  { character: '一', pinyin: 'yī', meaning: 'One', difficulty: 1, examples: ['丁', '七', '三'] },
  { character: '丨', pinyin: 'gǔn', meaning: 'Line', difficulty: 2, examples: ['中', '丰', '串'] },
  { character: '丶', pinyin: 'zhǔ', meaning: 'Dot', difficulty: 2, examples: ['丸', '丹', '主'] },
  { character: '丿', pinyin: 'piě', meaning: 'Slash', difficulty: 2, examples: ['九', '及', '升'] },
  { character: '乙', pinyin: 'yǐ', meaning: 'Second', difficulty: 2, examples: ['九', '乞', '乳'] },
  { character: '亅', pinyin: 'jué', meaning: 'Hook', difficulty: 2, examples: ['了', '矛', '予'] },
  { character: '二', pinyin: 'èr', meaning: 'Two', difficulty: 1, examples: ['于', '云', '些'] },
  { character: '亠', pinyin: 'tóu', meaning: 'Lid', difficulty: 2, examples: ['亡', '亢', '交'] },
  { character: '儿', pinyin: 'ér', meaning: 'Son / Legs', difficulty: 2, examples: ['兄', '兆', '先'] },
  { character: '入', pinyin: 'rù', meaning: 'Enter', difficulty: 2, examples: ['全', '两', '内'] },
  { character: '八', pinyin: 'bā', meaning: 'Eight', difficulty: 1, examples: ['公', '六', '共'] },
  { character: '冂', pinyin: 'jiǒng', meaning: 'Border', difficulty: 2, examples: ['内', '冈', '冉'] },
  { character: '冖', pinyin: 'mì', meaning: 'Cover', difficulty: 2, examples: ['冗', '写', '军'] },
  { character: '冫', pinyin: 'bīng', meaning: 'Ice', difficulty: 2, examples: ['冬', '冷', '冻'] },
  { character: '几', pinyin: 'jī', meaning: 'Table', difficulty: 2, examples: ['凡', '凤', '凭'] },
  { character: '凵', pinyin: 'qiǔ', meaning: 'Receptacle', difficulty: 3, examples: ['凶', '凸', '凹'] },
  { character: '刀', variant: '刂', pinyin: 'dāo', meaning: 'Knife', difficulty: 2, examples: ['切', '分', '利'] },
  { character: '力', pinyin: 'lì', meaning: 'Power / Strength', difficulty: 1, examples: ['加', '助', '勉'] },
  { character: '勹', pinyin: 'bāo', meaning: 'Wrap / Embrace', difficulty: 3, examples: ['勺', '匀', '勾'] },
  { character: '匕', pinyin: 'bǐ', meaning: 'Spoon', difficulty: 3, examples: ['北', '匙', '疑'] },
  { character: '匚', pinyin: 'fāng', meaning: 'Box', difficulty: 3, examples: ['匠', '匡', '匣'] },
  { character: '十', pinyin: 'shí', meaning: 'Ten', difficulty: 1, examples: ['千', '午', '南'] },
  { character: '卜', pinyin: 'bǔ', meaning: 'Divination', difficulty: 3, examples: ['占', '卡', '卧'] },
  { character: '卩', variant: '⻏', pinyin: 'jié', meaning: 'Seal', difficulty: 3, examples: ['卫', '印', '却'] },
  { character: '厂', pinyin: 'chǎng', meaning: 'Cliff', difficulty: 2, examples: ['厄', '历', '厚'] },
  { character: '厶', pinyin: 'sī', meaning: 'Private', difficulty: 3, examples: ['去', '县', '参'] },
  { character: '又', pinyin: 'yòu', meaning: 'Again', difficulty: 2, examples: ['叉', '及', '友'] },
  { character: '囗', pinyin: 'wéi', meaning: 'Enclosure', difficulty: 2, examples: ['回', '因', '国'] },
  { character: '士', pinyin: 'shì', meaning: 'Scholar / Soldier', difficulty: 2, examples: ['声', '壳', '壶'] },
  { character: '夂', pinyin: 'zhǐ', meaning: 'Go', difficulty: 3, examples: ['处', '备', '复'] },
  { character: '夕', pinyin: 'xī', meaning: 'Evening', difficulty: 2, examples: ['外', '多', '夜'] },
  { character: '大', pinyin: 'dà', meaning: 'Big / Large', difficulty: 1, examples: ['天', '太', '夫'] },
  { character: '宀', pinyin: 'mián', meaning: 'Roof', difficulty: 2, examples: ['安', '完', '客'] },
  { character: '寸', pinyin: 'cùn', meaning: 'Inch', difficulty: 3, examples: ['对', '封', '射'] },
  { character: '小', variant: '⺌', pinyin: 'xiǎo', meaning: 'Small', difficulty: 1, examples: ['少', '尖', '尘'] },
  { character: '尢', variant: '尣', pinyin: 'wāng', meaning: 'Lame', difficulty: 4, examples: ['尤', '尨', '就'] },
  { character: '尸', pinyin: 'shī', meaning: 'Corpse', difficulty: 3, examples: ['尼', '层', '属'] },
  { character: '屮', pinyin: 'chè', meaning: 'Sprout', difficulty: 4, examples: ['屯', '屮', '岔'] },
  { character: '巛', variant: '川', pinyin: 'chuān', meaning: 'River', difficulty: 2, examples: ['州', '巡', '巢'] },
  { character: '工', pinyin: 'gōng', meaning: 'Work', difficulty: 1, examples: ['左', '巧', '巨'] },
  { character: '己', pinyin: 'jǐ', meaning: 'Oneself', difficulty: 2, examples: ['已', '巳', '巷'] },
  { character: '巾', pinyin: 'jīn', meaning: 'Turban / Cloth', difficulty: 3, examples: ['布', '希', '帝'] },
  { character: '干', pinyin: 'gān', meaning: 'Dry', difficulty: 2, examples: ['平', '年', '并'] },
  { character: '幺', pinyin: 'yāo', meaning: 'Short Thread', difficulty: 4, examples: ['幻', '幼', '幽'] },
  { character: '广', pinyin: 'guǎng', meaning: 'Wide / House', difficulty: 2, examples: ['庄', '庆', '应'] },
  { character: '廴', pinyin: 'yǐn', meaning: 'Stride', difficulty: 4, examples: ['廷', '延', '建'] },
  { character: '廾', pinyin: 'gǒng', meaning: 'Hands Joined', difficulty: 4, examples: ['弄', '弃', '弊'] },
  { character: '弋', pinyin: 'yì', meaning: 'Shoot', difficulty: 4, examples: ['代', '式', '贰'] },
  { character: '弓', pinyin: 'gōng', meaning: 'Bow', difficulty: 2, examples: ['引', '弟', '张'] },
  { character: '彡', pinyin: 'shān', meaning: 'Bristle / Hair', difficulty: 4, examples: ['形', '彦', '彩'] },
  { character: '彳', pinyin: 'chì', meaning: 'Step', difficulty: 3, examples: ['往', '征', '律'] },
  { character: '戈', pinyin: 'gē', meaning: 'Spear', difficulty: 3, examples: ['戏', '战', '或'] },
  { character: '户', variant: '戶', pinyin: 'hù', meaning: 'Door / Household', difficulty: 3, examples: ['房', '戾', '扁'] },
  { character: '支', pinyin: 'zhī', meaning: 'Branch', difficulty: 3, examples: ['攱', '攲', '翅'] },
  { character: '攴', variant: '攵', pinyin: 'pū', meaning: 'Rap / Tap', difficulty: 3, examples: ['收', '改', '攻'] },
  { character: '文', pinyin: 'wén', meaning: 'Script / Literature', difficulty: 2, examples: ['斋', '斌', '斐'] },
  { character: '斗', pinyin: 'dǒu', meaning: 'Dipper', difficulty: 3, examples: ['料', '斜', '斟'] },
  { character: '斤', pinyin: 'jīn', meaning: 'Axe', difficulty: 3, examples: ['斥', '斩', '断'] },
  { character: '方', pinyin: 'fāng', meaning: 'Square', difficulty: 2, examples: ['放', '旅', '族'] },
  { character: '无', pinyin: 'wú', meaning: 'Not / Without', difficulty: 2, examples: ['既', '既', '芜'] },
  { character: '曰', pinyin: 'yuē', meaning: 'Say', difficulty: 3, examples: ['曲', '更', '曾'] },
  { character: '欠', pinyin: 'qiàn', meaning: 'Lack / Yawn', difficulty: 3, examples: ['次', '欣', '欲'] },
  { character: '止', pinyin: 'zhǐ', meaning: 'Stop', difficulty: 3, examples: ['正', '此', '武'] },
  { character: '歹', variant: '歺', pinyin: 'dǎi', meaning: 'Death / Bad', difficulty: 3, examples: ['死', '殃', '殇'] },
  { character: '殳', pinyin: 'shū', meaning: 'Weapon', difficulty: 4, examples: ['段', '殷', '殿'] },
  { character: '比', pinyin: 'bǐ', meaning: 'Compare', difficulty: 3, examples: ['毕', '毙', '毗'] },
  { character: '毛', pinyin: 'máo', meaning: 'Hair', difficulty: 2, examples: ['毫', '毯', '毫'] },
  { character: '氏', pinyin: 'shì', meaning: 'Clan', difficulty: 3, examples: ['民', '氓', '邸'] },
  { character: '气', pinyin: 'qì', meaning: 'Steam / Air', difficulty: 2, examples: ['氛', '氟', '氧'] },
  { character: '爪', variant: '爫', pinyin: 'zhǎo', meaning: 'Claw', difficulty: 3, examples: ['爬', '爱', '爵'] },
  { character: '父', pinyin: 'fù', meaning: 'Father', difficulty: 2, examples: ['爸', '爷', '爹'] },
  { character: '爿', variant: '丬', pinyin: 'qiáng', meaning: 'Half-tree trunk', difficulty: 4, examples: ['壮', '状', '将'] },
  { character: '片', pinyin: 'piàn', meaning: 'Slice', difficulty: 3, examples: ['版', '牌', '牒'] },
  { character: '牙', pinyin: 'yá', meaning: 'Fang / Tooth', difficulty: 3, examples: ['穿', '雅', '邪'] },
  { character: '牛', variant: '牜', pinyin: 'niú', meaning: 'Cow / Ox', difficulty: 2, examples: ['物', '牧', '特'] },
  { character: '犬', variant: '犭', pinyin: 'quǎn', meaning: 'Dog', difficulty: 2, examples: ['犯', '狂', '狐'] },
  { character: '玄', pinyin: 'xuán', meaning: 'Profound / Dark', difficulty: 4, examples: ['率', '兹', '玄'] },
  { character: '瓜', pinyin: 'guā', meaning: 'Melon', difficulty: 3, examples: ['瓠', '瓢', '瓣'] },
  { character: '瓦', pinyin: 'wǎ', meaning: 'Tile', difficulty: 4, examples: ['瓶', '瓷', '甄'] },
  { character: '甘', pinyin: 'gān', meaning: 'Sweet', difficulty: 3, examples: ['某', '甚', '甜'] },
  { character: '生', pinyin: 'shēng', meaning: 'Life', difficulty: 2, examples: ['产', '甥', '甦'] },
  { character: '用', pinyin: 'yòng', meaning: 'Use', difficulty: 2, examples: ['甩', '甫', '备'] },
  { character: '田', pinyin: 'tián', meaning: 'Field', difficulty: 2, examples: ['男', '界', '留'] },
  { character: '疋', variant: '⺪', pinyin: 'pǐ', meaning: 'Bolt of cloth', difficulty: 4, examples: ['疏', '疑', '疋'] },
  { character: '疒', pinyin: 'nè', meaning: 'Sickness', difficulty: 3, examples: ['病', '痛', '疗'] },
  { character: '癶', pinyin: 'bō', meaning: 'Back-to-back', difficulty: 4, examples: ['癸', '登', '发'] },
  { character: '白', pinyin: 'bái', meaning: 'White', difficulty: 2, examples: ['百', '皂', '皇'] },
  { character: '皮', pinyin: 'pí', meaning: 'Skin', difficulty: 3, examples: ['皱', '皲', '皴'] },
  { character: '皿', pinyin: 'mǐn', meaning: 'Dish', difficulty: 3, examples: ['盆', '益', '盛'] },
  { character: '矛', pinyin: 'máo', meaning: 'Spear', difficulty: 4, examples: ['矜', '柔', '矛'] },
  { character: '矢', pinyin: 'shǐ', meaning: 'Arrow', difficulty: 3, examples: ['知', '矩', '矮'] },
  { character: '石', pinyin: 'shí', meaning: 'Stone', difficulty: 2, examples: ['砍', '码', '硬'] },
  { character: '示', variant: '礻', pinyin: 'shì', meaning: 'Spirit / Show', difficulty: 3, examples: ['礼', '祝', '神'] },
  { character: '禸', pinyin: 'róu', meaning: 'Track', difficulty: 5, examples: ['禹', '离', '禽'] },
  { character: '穴', pinyin: 'xué', meaning: 'Cave', difficulty: 3, examples: ['空', '穿', '突'] },
  { character: '立', pinyin: 'lì', meaning: 'Stand', difficulty: 2, examples: ['站', '亲', '童'] },
  { character: '竹', variant: '⺮', pinyin: 'zhú', meaning: 'Bamboo', difficulty: 3, examples: ['笑', '笔', '答'] },
  { character: '米', pinyin: 'mǐ', meaning: 'Rice', difficulty: 3, examples: ['粉', '粗', '精'] },
  { character: '糸', variant: '纟', pinyin: 'mì', meaning: 'Silk', difficulty: 3, examples: ['红', '级', '线'] },
  { character: '缶', pinyin: 'fǒu', meaning: 'Jar', difficulty: 4, examples: ['缸', '缺', '罐'] },
  { character: '网', variant: '罒', pinyin: 'wǎng', meaning: 'Net', difficulty: 4, examples: ['罚', '罢', '罗'] },
  { character: '羊', variant: '⺶', pinyin: 'yáng', meaning: 'Sheep / Goat', difficulty: 3, examples: ['美', '着', '羡'] },
  { character: '羽', pinyin: 'yǔ', meaning: 'Feather', difficulty: 3, examples: ['扇', '翅', '翔'] },
  { character: '耳', pinyin: 'ěr', meaning: 'Ear', difficulty: 3, examples: ['取', '闻', '聚'] },
  { character: '舌', pinyin: 'shé', meaning: 'Tongue', difficulty: 3, examples: ['乱', '甜', '辞'] },
  { character: '舟', pinyin: 'zhōu', meaning: 'Boat', difficulty: 3, examples: ['般', '航', '船'] },
  { character: '虫', pinyin: 'chóng', meaning: 'Insect', difficulty: 3, examples: ['蛇', '蚁', '蜂'] },
  { character: '血', pinyin: 'xuè', meaning: 'Blood', difficulty: 4, examples: ['衄', '衅', '众'] },
  { character: '行', pinyin: 'xíng', meaning: 'Walk', difficulty: 2, examples: ['街', '术', '衙'] },
  { character: '衣', variant: '衤', pinyin: 'yī', meaning: 'Clothes', difficulty: 3, examples: ['衫', '补', '被'] },
  { character: '西', variant: '覀', pinyin: 'xī', meaning: 'West', difficulty: 3, examples: ['要', '栗', '票'] },
  { character: '艹', pinyin: 'cǎo', meaning: 'Grass', difficulty: 1, examples: ['花', '英', '苦'] },
];
